In [670]:
import random
from sklearn import metrics
from scipy import stats
from collections import defaultdict
import time

In [612]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans 

In [613]:
df = pd.read_csv('C:/Users/rakes/Downloads/iris.data', names = ["sepal_length", "sepal_width", "petal_length", "petal_width","class"])


In [614]:
df

sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [615]:
df["class"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [616]:
df['class']=df['class'].map({'Iris-setosa':0 ,  'Iris-versicolor':1 ,'Iris-virginica':2})

In [617]:
df

sepal_length  sepal_width  petal_length  petal_width  class
0             5.1          3.5           1.4          0.2      0
1             4.9          3.0           1.4          0.2      0
2             4.7          3.2           1.3          0.2      0
3             4.6          3.1           1.5          0.2      0
4             5.0          3.6           1.4          0.2      0
..            ...          ...           ...          ...    ...
145           6.7          3.0           5.2          2.3      2
146           6.3          2.5           5.0          1.9      2
147           6.5          3.0           5.2          2.0      2
148           6.2          3.4           5.4          2.3      2
149           5.9          3.0           5.1          1.8      2

[150 rows x 5 columns]

In [618]:
x = df.iloc[:, [0,1,2,3]].values
#clustering based on kmeans 
kmeans5 = KMeans(n_clusters=3)
y_kmeans5 = kmeans5.fit_predict(x)
print(y_kmeans5)

kmeans5.cluster_centers_

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 2 2 2 0 2 2 2 2
 2 2 0 0 2 2 2 2 0 2 0 2 0 2 2 0 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 2
 2 0]


array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.418     , 1.464     , 0.244     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [619]:
df["class"].unique()

array([0, 1, 2], dtype=int64)

In [620]:
K = 3
y = df.iloc[:,4].values

In [621]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [622]:
df['class'].values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [623]:
def Distancefn(point, centroid, distType):
     if( distType == "Euclidean"):
            dist = sum((point - centroid)**2)**0.5
            return dist
     elif( distType == "Cosine"):
        A = np.array(point)
        B = np.array(centroid)
        dist = 1 - np.dot(A,B)/(np.linalg.norm(A)*np.linalg.norm(B))
        return dist
     else:
        A = np.array(point)
        B = np.array(centroid)     
        dist = 1 - (np.sum(np.minimum(A,B), axis = 0)/np.sum(np.maximum(A, B), axis = 0)) 
        return dist       
    
def predictfn(classes, y, k =3):
    indexes = []
    for i in range(k):
        indexes.append(np.where(classes == i))
    for cluster in indexes:
        mode = int(stats.mode(y[cluster])[0])
        classes[cluster] = mode
    return classes    

In [642]:
for i in range(3):
    print(random.randint(i,len(y)))


82
6
32


In [671]:
def kmeansalg(data,y, k, distType):
    centroids = {}
    starttime = time.time()
    for i in range(k):
        centroids[i] = data[random.randint(i,len(y)-1)]
    classes = {}  
    classlabel = []
    SSE = []
    SSEvalue = 0
    iterations = 0
    while True:
        iterations = iterations + 1
        classes = {}
        classlabel = []
        for i in range(k):
            classes[i] = []
            
        for datapoint in data:
            distance = []
            
            for centroid in centroids:
                dist = Distancefn(datapoint, centroids[centroid], distType)
                distance.append(dist)
                
            minDist = min(distance)
            tempindex = distance.index(minDist)
            flag = 0
            for centroid in centroids:
                if((distance[centroid] == minDist) & (centroid != tempindex)):
                    flag = flag + 1
            if(flag == 0):        
                minindex = tempindex
                
            elif(flag == 1):
                minindex = random.randint(0,1)
            else:
                minindex = random.randint(0,2)    
            classes[minindex].append(datapoint)
            classlabel.append(minindex)
        oldCentroid = dict(centroids)
        
        for key in classes:
            classdata = classes[key]
            if(len(classdata)>0):
                newcentroid = np.mean(classdata, axis = 0)
                centroids[key] = newcentroid
                
        print(centroids) 
        ssevalue = 0
        for key in classes:
            for datapoint in classes[key]:
                ssevalue = ssevalue + Distancefn(datapoint, centroids[key], "Euclidean")
        SSE.append(ssevalue)
#         print(SSE)
        match = False;
        for key in oldCentroid:
            old = oldCentroid[key]
            new = centroids[key]
            if np.sum((new - old)/old * 100) < 0.01:
                match = True
            else: 
                match = False
                break
        if match:
            print("time " + str(time.time()-starttime))
            print("total iterations " + str(iterations) )
            
            print(centroids)
            return centroids, classlabel, classes, SSE 
            break   

In [672]:
def label_cluster(cluster, df):
    cl = defaultdict(int)
    for point in cluster:
        cl[point[-1]] += 1
    return cl

In [673]:
def alter(cluster, df):
    data = []
    cl = defaultdict(int)
    for point in cluster:
        dftemp = df[(df['sepal_length'] == point[0]) & (df['sepal_width'] == point[1]) & (df['petal_length'] == point[2]) & (df['petal_width'] == point[3])]
        dftemp = dftemp['class'].unique()
        cl[dftemp[-1]] += 1
    print(cl)
    return cl

In [676]:
centroids, classlabel, classes, SSE = kmeansalg(df.iloc[:, [0,1,2,3]].values,y, 3, "Euclidean")
print("centroids : ")
print(centroids)
print("SSE")
print(SSE)
classescount = [df[(df['class'] == 0)]['class'].count() , df[(df['class'] == 1)]['class'].count() , df[(df['class'] == 2)]['class'].count()]
print(classescount)
total = 0
correctcount = 0
for key in classes:
    d= dict(alter(classes[key], df))
    total += len(classes[key])
    mx = 0
    labelsize = 0
    
    for k in d: 
        if(mx < d[k]):
            mx = d[k]
    labelsize = mx
    correctcount += labelsize
print("accuracy")
print((correctcount/total)*100)
    


{0: array([5.006, 3.418, 1.464, 0.244]), 1: array([6.43125, 2.96875, 5.175  , 1.8025 ]), 2: array([5.585, 2.485, 3.83 , 1.17 ])}
{0: array([5.006, 3.418, 1.464, 0.244]), 1: array([6.55942029, 2.98550725, 5.3115942 , 1.87101449]), 2: array([5.6       , 2.61935484, 4.00322581, 1.24193548])}
{0: array([5.006, 3.418, 1.464, 0.244]), 1: array([6.59375  , 2.984375 , 5.3734375, 1.9078125]), 2: array([5.67222222, 2.67222222, 4.075     , 1.26388889])}
{0: array([5.006, 3.418, 1.464, 0.244]), 1: array([6.62833333, 3.00166667, 5.415     , 1.93      ]), 2: array([5.7125, 2.6775, 4.1425, 1.295 ])}
{0: array([5.006, 3.418, 1.464, 0.244]), 1: array([6.65090909, 3.01090909, 5.48727273, 1.96545455]), 2: array([5.78666667, 2.70222222, 4.19555556, 1.32222222])}
{0: array([5.006, 3.418, 1.464, 0.244]), 1: array([6.69215686, 3.01176471, 5.54117647, 1.98823529]), 2: array([5.81428571, 2.72653061, 4.24489796, 1.35102041])}
{0: array([5.006, 3.418, 1.464, 0.244]), 1: array([6.76956522, 3.03695652, 5.6       ,

In [677]:
centroids, classlabel, classes, SSE = kmeansalg(df.iloc[:, [0,1,2,3]].values,y, 3, "Cosine")
print("centroids : ")
print(centroids)
print("SSE")
print(SSE)
classescount = [df[(df['class'] == 0)]['class'].count() , df[(df['class'] == 1)]['class'].count() , df[(df['class'] == 2)]['class'].count()]
print(classescount)
total = 0
correctcount = 0
for key in classes:
    d= dict(alter(classes[key], df))
    total += len(classes[key])
    mx = 0
    labelsize = 0
    
    for k in d: 
        if(mx < d[k]):
            mx = d[k]
    labelsize = mx
    correctcount += labelsize
print("accuracy")
print((correctcount/total)*100)

{0: array([6.14705882, 2.88088235, 4.58088235, 1.57794118]), 1: array([5.006, 3.418, 1.464, 0.244]), 2: array([6.50625 , 2.853125, 5.596875, 1.884375])}
{0: array([6.03508772, 2.8245614 , 4.37894737, 1.42280702]), 1: array([5.006, 3.418, 1.464, 0.244]), 2: array([6.5627907 , 2.93488372, 5.60465116, 2.01162791])}
{0: array([5.9877551 , 2.79591837, 4.27959184, 1.34081633]), 1: array([5.006, 3.418, 1.464, 0.244]), 2: array([6.5254902 , 2.94509804, 5.50784314, 1.99803922])}
time 0.022937297821044922
total iterations 3
{0: array([5.9877551 , 2.79591837, 4.27959184, 1.34081633]), 1: array([5.006, 3.418, 1.464, 0.244]), 2: array([6.5254902 , 2.94509804, 5.50784314, 1.99803922])}
centroids : 
{0: array([5.9877551 , 2.79591837, 4.27959184, 1.34081633]), 1: array([5.006, 3.418, 1.464, 0.244]), 2: array([6.5254902 , 2.94509804, 5.50784314, 1.99803922])}
SSE
[116.48999270238271, 105.43478859287916, 103.05433581660319]
[50, 50, 50]
defaultdict(<class 'int'>, {1: 47, 2: 2})
defaultdict(<class 'int'>

In [682]:
centroids, classlabel, classes, SSE = kmeansalg(df.iloc[:, [0,1,2,3]].values,y, 3, "Jarcard")
print("centroids : ")
print(centroids)
print("SSE")
print(SSE)
classescount = [df[(df['class'] == 0)]['class'].count() , df[(df['class'] == 1)]['class'].count() , df[(df['class'] == 2)]['class'].count()]
print(classescount)
total = 0
correctcount = 0
for key in classes:
    d= dict(alter(classes[key], df))
    total += len(classes[key])
    mx = 0
    labelsize = 0
    
    for k in d: 
        if(mx < d[k]):
            mx = d[k]
    labelsize = mx
    correctcount += labelsize
print("accuracy")
print((correctcount/total)*100)

{0: array([5.46666667, 2.53809524, 3.84761905, 1.18095238]), 1: array([6.47341772, 2.96075949, 5.18734177, 1.80759494]), 2: array([5.006, 3.418, 1.464, 0.244])}
{0: array([5.55862069, 2.62413793, 3.97586207, 1.23103448]), 1: array([6.54929577, 2.97323944, 5.28591549, 1.85774648]), 2: array([5.006, 3.418, 1.464, 0.244])}
{0: array([5.65      , 2.64117647, 4.04705882, 1.25      ]), 1: array([6.57727273, 2.99090909, 5.34848485, 1.89545455]), 2: array([5.006, 3.418, 1.464, 0.244])}
{0: array([5.68378378, 2.67837838, 4.09189189, 1.26756757]), 1: array([6.6015873 , 2.98571429, 5.38412698, 1.91587302]), 2: array([5.006, 3.418, 1.464, 0.244])}
{0: array([5.69210526, 2.66578947, 4.11578947, 1.27368421]), 1: array([6.61129032, 2.9983871 , 5.39032258, 1.92258065]), 2: array([5.006, 3.418, 1.464, 0.244])}
{0: array([5.69210526, 2.66578947, 4.11578947, 1.27368421]), 1: array([6.61129032, 2.9983871 , 5.39032258, 1.92258065]), 2: array([5.006, 3.418, 1.464, 0.244])}
time 0.04304981231689453
total ite

In [685]:
def Alter1kmeansalg(data,y, k, distType):
    centroids = {}
    starttime = time.time()
    for i in range(k):
        centroids[i] = data[random.randint(i,len(y)-1)]
    classes = {}  
    classlabel = []
    SSE = []
    SSEvalue = 0
    iterations = 0
    while True:
        iterations = iterations + 1
        classes = {}
        classlabel = []
        for i in range(k):
            classes[i] = []
            
        for datapoint in data:
            distance = []
            
            for centroid in centroids:
                dist = Distancefn(datapoint, centroids[centroid], distType)
                distance.append(dist)
                
            minDist = min(distance)
            tempindex = distance.index(minDist)
            flag = 0
            for centroid in centroids:
                if((distance[centroid] == minDist) & (centroid != tempindex)):
                    flag = flag + 1
            if(flag == 0):        
                minindex = tempindex
                
            elif(flag == 1):
                minindex = random.randint(0,1)
            else:
                minindex = random.randint(0,2)    
            classes[minindex].append(datapoint)
            classlabel.append(minindex)
        oldCentroid = dict(centroids)
        
#         for key in classes:
#             classdata = classes[key]
#             if(len(classdata)>0):
#                 newcentroid = np.mean(classdata, axis = 0)
#                 centroids[key] = newcentroid
                
#         print(centroids) 
        ssevalue = 0
        for key in classes:
            for datapoint in classes[key]:
                ssevalue = ssevalue + Distancefn(datapoint, centroids[key], "Euclidean")
        SSE.append(ssevalue)
#         print(SSE)
        match = False;
        for key in oldCentroid:
            old = oldCentroid[key]
            new = centroids[key]
            if np.sum((new - old)/old * 100) < 0.01:
                match = True
            else: 
                match = False
                break
        if(iterations == 2):
            match = True
        if match:
            print("time " + str(time.time()-starttime))
            print("total iterations " + str(iterations) )
            
            print(centroids)
            return centroids, classlabel, classes, SSE 
            break   

In [684]:
centroids, SSE = Alter1kmeansalg(df.iloc[:, [0,1,2,3]].values,y, 3, "Euclidean")
print("centroids : ")
print(centroids)
print("SSE")
print(SSE)

time 0.0029916763305664062
total iterations 1
{0: array([6.1, 2.9, 4.7, 1.4]), 1: array([5.2, 3.5, 1.5, 0.2]), 2: array([6.6, 2.9, 4.6, 1.3])}


ValueError: too many values to unpack (expected 2)